config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root "projects#index"

  get '/contacts', to: 'static_pages#contacts'
  get '/about', to: 'static_pages#about'
  
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/profile/user/edit/:id', to: 'users#edit', as: "edit_profile"
  post '/profile/user/edit/:id', to: 'users#update'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/projects', to: 'projects#index', as: "projects"
  get '/projects/new', to: 'projects#new', as: "new_projects"
  post '/projects/new', to: 'projects#create'
  get '/projects/:id', to: 'projects#show', as: "project"
  get '/projects/edit/:id', to: 'projects#edit', as: "edit_project"
  post '/projects/edit/:id', to: 'projects#update'
  delete '/projects/:id', to: "projects#delete"

  post '/projects/:post_id', to: 'donations#create'
  delete '/projects/:post_id', to: 'donations#destroy'

  resources :posts do 
    resources :donations
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]
  def index
    @post = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end
  
  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  def create
    @user = current_user
    @post = @user.posts.create(post_params)
    @post.current = 0
    if @post.save
      flash[:success] = "Your project post was created!"
      redirect_to project_path(@post)
    else
      render 'new'
    end
  end

  def update 
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to project_path(@post)
    else 
      render 'edit'
    end
  end

  def delete
    @post =  Post.find(params[:id])
    @post.destroy

    redirect_to root_path
  end

  private
    def post_params
      params.require(:post).permit(:title,:content, :goal)
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_path
      end
    end

    def correct_user
      @post = Post.find(params[:id])
      redirect_to (login_path) unless current_user.id != @post.user
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @post, url: {action: yield(:action)}, :method => :POST  do |f| %>
  <%= render 'shared/error_messages', object: @post %>

    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>

    <%= f.label :content, "Post Content" %>
    <%= f.cktext_area :content, placeholder: "Please put your content here..." %>

    <%= f.label :goal, "Money Goal" %>
    <%= f.number_field :goal%>
    
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/projects/_project.html.erb
<tr scope="row" id='project-id-<%post.id%>'>
    <td><%= link_to post.title , project_path(post) %></td>
    <td><p><%= post.current %>$ out of <%= post.goal %>$</p></td>
</tr>

app/views/projects/edit.html.erb
<% provide(:title, 'Editing Project') %>
<% provide(:button_text, 'Save changes')%>
<% provide(:action, 'update')%>

<h1>Editing Project</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
      <%= render 'form' %>
  </div>
</div>

app/views/projects/index.html.erb
<% if !@post.empty? %>
    <h1>All projects</h1>

    <table class="table table-dark">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Progress</th>
                </tr>
            </thead>    
            <tbody>
                <% @post.each do |post| %>
                    <%= render 'project', :post => post%>
                <% end %>
            </tbody>
    </table>
<% else %>
    <h1>There no projects yet</h1>
<% end %>

app/views/projects/new.html.erb
<% provide(:title, 'New Project') %>
<% provide(:button_text, 'Create project')%>
<% provide(:action, 'create')%>

<h1>New Project</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form'%>
  </div>
</div>

app/views/projects/show.html.erb
<% provide(:title, @post.title) %>
<div class="center jumbotron">

    <div class = "post">
        <p class= "post-title"><%= @post.title %><p>
        
        <div class= "post-content">
            <%=raw @post.content %>
        </div>

        <p class="gather-progress"><%= @post.current %>$ out of <%= @post.goal %>$<p>
    </div>
    
    <% if logged_in? && @post.user_id == current_user.id%>
        <%= link_to 'Edit', edit_project_path(@post) %>
        <%= link_to 'Delete', project_path(@post), 
                            method: :delete,
                            data: { confirm: 'Are you sure?' } %>
    <% end %>

    <%= render 'donations/donations'%>

</div>