config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root "projects#index"

  get '/contacts', to: 'static_pages#contacts'
  get '/about', to: 'static_pages#about'
  
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/profile/user/edit/:id', to: 'users#edit', as: "edit_profile"
  post '/profile/user/edit/:id', to: 'users#update'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/projects', to: 'projects#index', as: "projects"
  get '/projects/new', to: 'projects#new', as: "new_projects"
  post '/projects/new', to: 'projects#create'
  get '/projects/:id', to: 'projects#show', as: "project"
  get '/projects/edit/:id', to: 'projects#edit', as: "edit_project"
  post '/projects/edit/:id', to: 'projects#update'
  delete '/projects/:id', to: "projects#delete"

  post '/projects/:post_id', to: 'donations#create'
  delete '/projects/:post_id', to: 'donations#destroy'

  resources :posts do 
    resources :donations
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="#">E-Crowdfunding System</a>
    by <a href="#">Fedorovich Oleg</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '/about' %></li>
      <li><%= link_to "Contact", '/contacts' %></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <%= link_to "Good Idea", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-left">
      <% if logged_in? %>
        <li><%= link_to "Start Project", '/projects/new', class: "hvr-shutter-out-horizontal"%></li>      <% end %>
      </ul>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit profile", edit_profile_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  = javascript_include_tag Ckeditor.cdn_url
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Good Idea</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
          <%# <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/layouts/application.html.slim
= javascript_include_tag Ckeditor.cdn_url